/**
 * SynoLinks - Secure TLS Connection
 *
 * Connects to SynoLinks MQTT broker using TLS encryption.
 * All data between device and server is encrypted.
 *
 * IMPORTANT: Replace the CA certificate below with your server's CA cert.
 * Generate certs: scripts/generate-mqtt-certs.sh your-domain.com
 * Then copy the contents of ca.crt here.
 *
 * Hardware: ESP32 or ESP8266
 */

#include <SynoLinks.h>

#define AUTH_TOKEN  "YourDeviceAuthToken"
#define ORG_ID     "YourOrgId"
#define MQTT_HOST  "your-server.com"

char ssid[] = "YourWiFiSSID";
char pass[] = "YourWiFiPassword";

// CA Certificate - paste your ca.crt content here
// Generated by: scripts/generate-mqtt-certs.sh
const char* ca_cert = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
... paste your ca.crt content here ...
-----END CERTIFICATE-----
)EOF";

SynoLinks syno(AUTH_TOKEN, ORG_ID, MQTT_HOST, 8883);

void setup() {
  Serial.begin(115200);

  // Enable TLS with CA certificate (MUST call before begin!)
  syno.setTLSCert(ca_cert);

  // If you want to skip certificate verification (development only!):
  // syno.setTLSCert(nullptr);  // WARNING: insecure, vulnerable to MITM

  syno.begin(ssid, pass);
}

void loop() {
  syno.run();

  static unsigned long lastSend = 0;
  if (millis() - lastSend > 5000) {
    lastSend = millis();
    syno.virtualWrite(V0, WiFi.RSSI());
    Serial.printf("Sent RSSI: %d dBm (TLS encrypted)\n", WiFi.RSSI());
  }
}
